{
 "title": "nmon Dashboard",
 "description": "nmon 데이터를 기반으로 모니터링하는 대시보드",
 "tags": [
  "nmon",
  "ubuntu",
  "linux"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Memory Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Total Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "memtotal" }
     ]
    },
    {
     "alias": "Free Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "memfree" }
     ]
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU_ALL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "User%" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU_ALL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Sys%" }
     ]
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "active" }
     ]
    },
    {
     "alias": "cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "cached" }
     ]
    },
    {
     "alias": "buffers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "buffers" }
     ]
    },
    {
     "alias": "Total Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "memtotal" }
     ]
    }
   ]
  },
  {
   "title": "enp1s0 - Inbount (KB/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "enp1s0 - Inbount (KB/s)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NET",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "enp1s0-read-KB/s" }
     ]
    }
   ]
  },
  {
   "title": "enp1s0 - Outbount (KB/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "enp1s0 - Outbount (KB/s)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NET",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "enp1s0-write-KB/s" }
     ]
    }
   ]
  }
 ]
}