version: '2'

services:
  influxdb:
    build: influxdb
    image: invesume/influxdb
    container_name: ivs-influxdb
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    build: grafana
    image: invesume/grafana
    container_name: ivs-grafana
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
