{
 "title": "JIRA Server Dashboard",
 "description": "nmon 데이터를 기반으로 모니터링하는 대시보드",
 "tags": [
  "nmon",
  "ubuntu",
  "linux"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "JIRA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "생성된 지라 이슈 수",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM\n  jiraissue\n"
    }
   ]
  },
  {
   "title": "hckim 의 미해결 이슈(IVS-18)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM jiraissue where assignee='hckim' AND project='10014' AND resolution='10000' ;"
    }
   ]
  },
  {
   "title": "DB connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(1) from pg_stat_activity where usename != 'telegraf';"
    }
   ]
  },
  {
   "title": "생성된 그룹",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(ID) FROM cwd_group;"
    }
   ]
  },
  {
   "title": "지라 사용자 수",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(ID) FROM cwd_user;"
    }
   ]
  },
  {
   "title": "총 프로젝트",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "SELECT COUNT(ID) FROM project;" }
   ]
  },
  { "title": "System - pms.invesume.com", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 } },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU_ALL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Idle%" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "memtotal" }
     ]
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "active" }
     ]
    },
    {
     "alias": "cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "cached" }
     ]
    },
    {
     "alias": "buffers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "buffers" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "memfree" }
     ]
    }
   ]
  },
  {
   "title": "CPU - User %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU_ALL",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "User%" }
     ]
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU_ALL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "User%" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU_ALL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Sys%" }
     ]
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MEM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "memfree" }
     ]
    }
   ]
  },
  {
   "title": "enp1s0 - Inbount (KB/s)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "enp1s0 - Inbount (KB/s)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NET",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "enp1s0-read-KB/s" }
     ]
    }
   ]
  },
  {
   "title": "enp1s0 - Outbount (KB/s)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "enp1s0 - Outbount (KB/s)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NET",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "enp1s0-write-KB/s" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "sda READ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DISKREAD",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "sda WRITE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DISKWRITE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pms" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" }
     ]
    }
   ]
  }
 ]
}